# Generated by Django 4.1.7 on 2023-03-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='uuid',
            new_name='link_id',
        ),
    ]
